# Introduction to Packages in Python
In Python, a package is a way to organize related modules and provide a hierarchical structure to the code. It allows for better code organization, modularity, and reusability. A package is simply a directory (or a folder) that contains Python modules and an additional file called __init__.py. The __init__.py file marks the directory as a Python package.

Packages are used to group related functionality together, making it easier to manage and reuse code. They enable you to organize your code into meaningful units, create namespaces, and avoid naming conflicts.


### Exercise: Creating and Using a Simple Package

Create a new directory ***under the folder where the running notebook is stored*** on your computer to serve as the package folder. Give it a meaningful name, such as "my_package".

Inside the "my_package" folder, create a new Python file called my_module.py. This will be one of the modules within your package.

Write some functions and/or a class inside the my_module.py file. These functions and/or class should provide some specific functionality that can be useful for other programs.

In the same "my_package" folder, create another Python file called __init__.py. This file is required to mark the directory as a package.

Now, you have your package set up. You can use it in a Jupyter notebook or any other Python script by importing it using the package name and module name.

Example:

Let's say your package "my_package" contains a module called my_module.py with the following functions:

```python
# my_module.py

def greet(name):
    print(f"Hello, {name}!")

def square(n):
    return n * n
```

To use this package and its module in a Jupyter notebook:

Save the "my_package" folder in the same directory as your Jupyter notebook.

In the notebook, import the package and module as follows:

```python
from my_package import my_module

my_module.greet("Alice")  # Output: Hello, Alice!

result = my_module.square(5)
print(result)  # Output: 25
```


- In Jupyter Notebook, the ! (exclamation mark) symbol is used to execute shell commands directly from a code cell. When you use ! followed by a command, Jupyter Notebook will treat it as a shell command and execute it in the underlying operating system.
- You can use the `!pip install` command to install packages directly from the notebook itself. This command allows you to install Python packages that are not already available in your environment.

In [ ]:
!pip install numpy
!pip install tqdm
!pip install imageio
!pip install Pillow # PIL
!pip install matplotlib
!pip install opencv-python # cv2

### Exercise: Download and Open Images from URL
In this exercise, we will practice using packages to download and open images from a URL. We will also introduce the concept of image representation using the PIL (Python Imaging Library) and cv2 (OpenCV) packages. **With the help of ChatGPT**:

1. First, use `urllib.request` to download an image from the provided URL: "https://cdn.vox-cdn.com/uploads/chorus_image/image/47413330/the-simpsons-tv-series-cast-wallpaper-109911.0.0.jpeg". Save the downloaded image to a local file.

2. Next, use the `PIL.Image` package to display the downloaded image. `PIL.Image` provides a convenient way to open and manipulate images in Python.

3. Then, use the `cv2.imread` function from the OpenCV package to load the downloaded image file. OpenCV is a powerful library for image processing and computer vision tasks. What is the format of the loaded image?

4. Convert it from the cv2 format to a PIL image.

In [ ]:
import urllib.request
from PIL import Image
from IPython.display import display

# Download and save the image from the URL
# URL of the image
image_url = "https://cdn.vox-cdn.com/uploads/chorus_image/image/47413330/the-simpsons-tv-series-cast-wallpaper-109911.0.0.jpeg"

# Specify the local filename to save the image
filename = "image.jpg"

# Download the image; you can find it under the folder where the running notebook is stored  
urllib.request.urlretrieve(image_url, filename)

# Open the image using PIL.Image
image = Image.open(filename)

# Display the image within the Jupyter Notebook
display(image)



In [ ]:
import cv2
# Load the downloaded image using cv2.imread
image_cv2 = cv2.imread(filename)
print(image_cv2)

In [ ]:
# Convert the cv2 image to PIL image
image_pil_converted = Image.fromarray(cv2.cvtColor(image_cv2, cv2.COLOR_BGR2RGB))
display(image_pil_converted)

#### PIL (Python Imaging Library):
- PIL is a popular library in Python for handling and manipulating images.
- It provides a wide range of functions and methods to perform operations on images, such as opening, saving, resizing, cropping, and applying various filters and transformations.
- PIL supports a variety of image file formats, including JPEG, PNG, GIF, BMP, and TIFF.
- It is widely used for tasks like image processing, computer vision, generating thumbnails, and creating visualizations.


#### cv2 (OpenCV):
- OpenCV (Open Source Computer Vision) is a powerful open-source library for computer vision and image processing tasks.
- It offers a comprehensive set of functions and tools for working with images, videos, and real-time computer vision applications.
- OpenCV provides a wide range of capabilities, including image and video capturing, image filtering, feature detection, object recognition, and camera calibration.
- It supports various programming languages, including Python, C++, and Java, making it highly versatile and widely used in both research and industry.


## Image Representation
ref: 
- https://github.com/photosbyjeremy/img_qc_workshop/
- https://ai.stanford.edu/~syyeung/cvweb/tutorial1.html

### Pixels
The pixel is the basic building block of the image and is defined by its intensity (think *value from dark to light*) and possibly its channel. The range of intensities can vary as can the number and type of channels.

Bitonal, or black & white pixels, have two possible intensities: black and white. A grayscale image pixel's intensity varies with the bit-depth of the pixel.


### Bit Depth

In an **8-bit grayscale** digital image, the intensity (think *value from dark to light*) of each pixel is defined by 8 individual bits.

A bit can either be on, with a value of 1, or off, with a value of 0.

We can find the total number of possible intensities by finding the total possible mathematical combinations for each bit of the pixel. This is done mathematically by raising the total **bit_possibilities** to the power of the number of **bits_per_pixel**.

![](http://hosting.soonet.ca/eliris/remotesensing/LectureImages/pixel.gif)
<img src="https://ai.stanford.edu/~syyeung/cvweb/Pictures1/colorpixels.png" alt="image" width="300">


In [ ]:
bit_possibilities, bits_per_pixel = 2, 8
possible_intensities = bit_possibilities ** bits_per_pixel
possible_intensities

### Color Channels

Expanding our discussion to include 24-bit RGB color images, we first break the 24-bits per pixel down into individual color channels. Each 24-bit RGB color image pixel is made up of 3 * 8-bit color channels: Red (R), Green (G), and Blue (B).

![RGB_exp_1](https://upload.wikimedia.org/wikipedia/commons/5/56/RGB_channels_separation.png)

![RGB_exp_2](https://www.theclickreader.com/wp-content/uploads/2020/08/color-channels-RGB.jpg)

To compute the total **possible_intensities** for a 24-bit RGB color image pixel first define the **bits_per_pixel** as **bits_per_channel** * **number_of_channels**.


In [ ]:
bit_possibilities, bits_per_channel, number_of_channels = 2, 8, 3
bits_per_pixel = bits_per_channel * number_of_channels  # 8 * 3
bits_per_pixel

In [ ]:
possible_intensities = bit_possibilities ** bits_per_pixel  # 2 ** 24

possible_intensities

So with 3 channels of 256 **possible_intensities** there are 1.67 million possibilities for each pixel in a 24-bit RGB color image.

### Basic Image Processing with PIL.Image
read more [here](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html)

#### Open Image Files

`PIL.Image.open()`:

- The PIL (Python Imaging Library) module provides a way to open and manipulate image files.
- When we use the PIL.Image.open() function, we can load an image file and create a PIL Image object.
- This object represents the image in memory and allows us to perform various operations on it.

In [ ]:
pil_img = Image.open('image.jpg')

In [ ]:
# For an Image object, you can use instance attributes to examine the file contents:
print(pil_img.format, pil_img.size, pil_img.mode)

#### Resize an image

When resizing an image, there are different algorithms that can be used to determine how the image is transformed. Some common resize algorithms include:

- Nearest-neighbor interpolation: This algorithm selects the nearest pixel to determine the new pixel value. It is a fast algorithm but may result in a loss of image quality, particularly when scaling down.

- Bilinear interpolation: This algorithm calculates the new pixel value by taking a weighted average of the surrounding four pixels. It provides smoother results compared to nearest-neighbor interpolation.

- Bicubic interpolation: This algorithm is an extension of bilinear interpolation, using a larger neighborhood of pixels to calculate the new pixel value. It produces smoother results and can preserve more details, but it may also introduce some blurring.***

- When using the resize() method in PIL, you can specify the desired size of the output image as a tuple of width and height. Additionally, you can provide an optional resample parameter to choose the resize algorithm. By default, it uses a high-quality resampling algorithm called "Lanczos".

In [ ]:
# Use the .resize() method to resize the image to a specific width and height or a scaling factor.
default_resize = pil_img.resize((300,300))
default_resize

In [ ]:
nearest_resize = pil_img.resize((300,300), Image.NEAREST)
nearest_resize

Matplotlib is a popular Python library used for creating visualizations and plots. It provides a wide range of tools and functions for generating various types of plots, such as line plots, scatter plots, bar plots, histograms, and more. Matplotlib is widely used in fields such as data analysis, scientific research, and data visualization.

In [ ]:
from matplotlib import pyplot as plt
#This line imports the pyplot module from the matplotlib library, 
# which provides a convenient interface for creating and customizing plots and visualizations.
fig, axs = plt.subplots(1, 2)
# This line creates a figure (fig) and a set of subplots (axs) using the subplots() function from pyplot. 
# In this case, it creates a single row with two subplots arranged side by side.
axs[0].imshow(default_resize)
axs[1].imshow(nearest_resize)
# These lines use the imshow() function to display images within the subplots.
plt.show()
# The show() function from pyplot is called to render the plot on the screen and make it visible to the user.

In [ ]:
# save figure object to local file
fig.savefig('my_fig.jpg')

In [ ]:
chess_board_img = Image.open('chess_board.png')
chess_board_img

In [ ]:
chess_board_img.resize((500,500))

In [ ]:
chess_board_img.resize((500,500), Image.NEAREST)

#### Crop an image

Use the .crop() method to select and extract a specific region or area of interest from the image.

In [ ]:
pil_img.crop((0,100, 50,150)) # Example crop coordinates (left, upper, right, lower)

#### Rotate an image

In [ ]:
# Use the .rotate() method to rotate the image by a specified angle in degrees.
pil_img.rotate(-10)

#### Convert image formats

In [ ]:
# Use the .convert() method to convert the image to a different color mode or file format.
grey_image = pil_img.convert('L')
print(grey_image.format, grey_image.size, grey_image.mode)
grey_image

In [ ]:
# you can use help() function or Shift+Tab if you want to know more about a method.
help(pil_img.convert)

**Image filtering**:

Spatial image filtering, also known as convolution, is a fundamental technique used for various image processing tasks, such as blurring, sharpening, edge detection, and more. It involves applying a filter or a kernel to an image to perform local operations on each pixel.

The filter, usually represented as a small matrix or kernel, is a set of weights that define how each pixel in the neighborhood contributes to the output. The size of the filter determines the spatial extent of the local operation.

To apply the convolution operation, we start by placing the center of the filter on a pixel in the image. Then, for each pixel in the filter's neighborhood, we multiply the corresponding filter weight with the corresponding pixel value. These products are summed up, and the result becomes the new value of the pixel under the filter's center.

We repeat this process for every pixel in the image, sliding the filter across the entire image and computing the new pixel values based on the filter weights and the pixel values in the neighborhood. This process effectively combines the information from nearby pixels to create the filtered output.

The key idea behind convolution is that the filter's weights determine the type of operation being performed. For example, a blurring filter might have equal weights to average the pixel values, while an edge detection filter might have positive and negative weights to enhance edges.

By applying different filters and adjusting their weights, we can achieve various image processing effects. Convolution is a powerful technique that allows us to manipulate and enhance images based on their local pixel neighborhoods, providing us with the ability to extract meaningful features and enhance image details
![](https://theailearner.com/wp-content/uploads/2019/04/full_padding_no_strides.gif)
![](https://ai.stanford.edu/~syyeung/cvweb/gifs/moving%20average.gif)

#### Apply image filters

In [ ]:
from PIL import ImageFilter
# The Box Blur filter is a simple blurring technique that applies a box-shaped kernel to the image. 
# It calculates the average value of the pixels within the kernel and replaces the center pixel with this average value. 
# This filter helps to reduce noise and smooth out the image.
pil_img.filter(ImageFilter.BoxBlur(radius=5))

In [ ]:
# The Gaussian Blur filter applies a Gaussian kernel to the image, 
# which gives a softer and more natural-looking blur compared to the Box Blur. 
# It uses a weighted average of nearby pixels, with more weight assigned to pixels closer to the center of the kernel. 
# This filter is effective in reducing noise and creating a gentle blur effect.
pil_img.filter(ImageFilter.GaussianBlur(radius=5))
# try to use a smaller radius

In [ ]:
# The Edge Enhance More filter enhances the edges in an image, making them more pronounced and distinctive. 
# It achieves this by applying a specific convolution kernel that amplifies the differences in intensity between neighboring pixels. 
# This filter is useful for highlighting edges and details in an image.
pil_img.filter(ImageFilter.EDGE_ENHANCE_MORE())

#### Save image
To save an edited image, use .save() method

In [ ]:
# note that the above operation are not inplace modification
blurred_img = pil_img.filter(ImageFilter.GaussianBlur(5))
blurred_img.save('blurred_image.jpg')

In [ ]:
Image.open('blurred_image.jpg')

#### Exercise: Basic Image Processing and Display

- Load an image of your choice using PIL.
- Resize the image to a smaller size using the resize method.
- Convert the resized image to grayscale using the convert method.
- Apply a rotation of 45 degrees to the grayscale image using the rotate method.
- Crop a specific region of interest from the rotated image using the crop method.
- Display the original image, the resized image, the grayscale image, the rotated image, and the cropped image together using plt.subplot.


- Hint:
    - Use PIL.Image.open() to load the image.
    - Use the resize method to resize the image.
    - Use the convert method with the argument 'L' to convert the image to grayscale.
    - Use the rotate method to rotate the image by a specified angle.
    - Use the crop method to select and extract a specific region of interest.
    - Use plt.subplot to create a grid of subplots and display the images.

In [ ]:
import PIL.Image as Image
import matplotlib.pyplot as plt

# 1. Load the image
image = Image.open('image.jpg')

# 2. Resize the image
resized_image = image.resize((200, 200))

# 3. Convert to grayscale
grayscale_image = resized_image.convert('L')

# 4. Rotate the image
rotated_image = grayscale_image.rotate(45)

# 5. Crop a region of interest
crop_coords = (50, 50, 150, 150)  # Example crop coordinates (left, upper, right, lower)
cropped_image = rotated_image.crop(crop_coords)

# 6. Display the images together using subplots
plt.figure(figsize=(10, 10))

# Original image
plt.subplot(2, 3, 1)
plt.imshow(image)
plt.title('Original Image')

# Resized image
plt.subplot(2, 3, 2)
plt.imshow(resized_image)
plt.title('Resized Image')

# Grayscale image
plt.subplot(2, 3, 3)
plt.imshow(grayscale_image, cmap='gray')
plt.title('Grayscale Image')

# Rotated image
plt.subplot(2, 3, 4)
plt.imshow(rotated_image, cmap='gray')
plt.title('Rotated Image')

# Cropped image
plt.subplot(2, 3, 5)
plt.imshow(cropped_image, cmap='gray')
plt.title('Cropped Image')

#The plt.tight_layout() function is a utility function provided by Matplotlib that adjusts the spacing between subplots to ensure that the plot elements do not overlap with each other. It is typically used when multiple subplots are created within a single figure.
plt.tight_layout()

#This line displays the figure containing the subplots and the images.
plt.show()



2. `cv2.imread()`:
- The cv2 (OpenCV) library is widely used for computer vision and image processing tasks.
- The cv2.imread() function allows us to read an image file and create a NumPy array representation of the image.
- The NumPy array stores the pixel values of the image, allowing us to perform numerical operations and transformations on the image.

In [ ]:
image_array = cv2.imread('image.jpg')
image_array.shape

In [ ]:
# the color channel order differs between the two libraries.
# In OpenCV (cv2), the default channel order is Blue-Green-Red (BGR), whereas in PIL (Python Imaging Library), the default channel order is Red-Green-Blue (RGB). Therefore, directly using Image.fromarray() on an array obtained from cv2.imread() will result in an image with incorrect color representation.
Image.fromarray(image_array)

In [ ]:
# here we define a function to convert image array to PIL image
def convert_cv2_to_pil(image_array):
    color_converted = cv2.cvtColor(image_array, cv2.COLOR_BGR2RGB)
    pil_image=Image.fromarray(color_converted)
    return pil_image

In [ ]:
convert_cv2_to_pil(image_array)

In [ ]:
# crop
# the slice of the image array to be extracted. 
# In this case, it selects rows 80 to 149 (150-80) and columns 0 to 199 (200-0), 
# including all channels represented by : 
cropped_array = image_array[80:150,0:200,:]

cropped = convert_cv2_to_pil(cropped_array)
cropped

In [ ]:
# brightness
# divides each pixel value in the image array by 2, 
# reducing the brightness of the image by half.
convert_cv2_to_pil(image_array//2)

In [ ]:
# color channel

copied_image_array = image_array.copy()
#  sets all values in the blue channel (index 0) to 0
copied_image_array[:,:,0] = 0
#  sets all values in the green channel (index 1) to 0
copied_image_array[:,:,1] = 0
red_channel = convert_cv2_to_pil(copied_image_array)


copied_image_array = image_array.copy()
copied_image_array[:,:,1] = 0
copied_image_array[:,:,2] = 0
blue_channel = convert_cv2_to_pil(copied_image_array)


copied_image_array = image_array.copy()
copied_image_array[:,:,0] = 0
copied_image_array[:,:,2] = 0
green_channel = convert_cv2_to_pil(copied_image_array)

In [ ]:
fig, axs = plt.subplots(2, 2)
axs[0, 0].imshow(red_channel)
axs[0, 1].imshow(blue_channel)
axs[1, 0].imshow(green_channel)
axs[1, 1].imshow(image)
plt.tight_layout()
plt.show()

#### Mini Project:
creating a sliding window to crop an image and then concatenating the cropped frames into a GIF-like short video:

1. Load an input image:
- Use the cv2.imread() function to read an input image from a file.

2. Define the sliding window parameters:
- Set the sliding window size and stride according to your desired configuration.

3. Create the sliding window:
- Using nested loops, iterate over the image pixels with the defined sliding window size and stride.
- At each iteration, extract the sub-image within the sliding window boundaries.

4. Concatenate the cropped frames into a GIF-like short video:
- Create an empty list to store the cropped frames.
- For each cropped frame, append it to the list of frames.

5. Save the frames as a GIF file:
- Use the imageio library to save the list of frames as a GIF file.


In [ ]:
import cv2
import imageio
from tqdm import tqdm

# Load the input image
image = cv2.imread('image.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

scale_percent = 20       # percent of original size
width = int(image.shape[1] * scale_percent / 100)
height = int(image.shape[0] * scale_percent / 100)
dim = (width, height)
image = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)

# Define the sliding window parameters (window size and stride)
window_size = (image.shape[0], image.shape[0])
stride = 1

# Create an empty list to store the cropped frames
frames = []

# Create the sliding window
# To use tqdm, you typically wrap your iterable with the tqdm function and iterate over it. 
# It will automatically generate a progress bar based on the length of the iterable.
for x in tqdm(range(0, image.shape[1] - window_size[1] + 1, stride)):
    # Crop the sub-image within the sliding window boundaries
    cropped_frame = image[:, x:x+window_size[1]]

    # Append the cropped frame to the list of frames
    frames.append(cropped_frame)

In [ ]:
# Save the frames as a GIF file
imageio.mimsave('output.gif', frames, duration=169/60)

#### Mini Project

1. Read the links from the input text file:
- Open the input text file using the open() function.
- Read the contents of the file using the readlines() method.
- Store the links in a list.
- Download the images:

2. Iterate through the list of links.
- Use a loop to download each image using a library like requests or urllib.
- Handle exceptions using a try-except block to catch any errors that may occur during the download process.
- If an exception is raised, log the error message to a log file.

3. Create a log file:
- Open a log file using the open() function with the appropriate mode.
- Within the try-except block, write the error messages to the log file when an exception occurs.

In [ ]:
import requests

# Read the links from the input text file
with open('image_link.txt', 'r') as file:
    links = file.readlines()

# Remove any leading/trailing whitespace or newline characters from the links
links = [link.strip() for link in links]

# Download the images, save them as local files, and log any errors to a log file
with open('log.txt', 'w') as log_file:
    for i, link in enumerate(links):
        try:
            # Download the image using a library like requests or urllib
            response = requests.get(link)

            # Check the response status code (200 if the download is successful) to ensure successful download
            if response.status_code == 200:
                # Generate a unique filename based on the link index
                filename = f'image_{i}.jpg'

                # Save the image as a local file
                with open(filename, 'wb') as image_file:
                    """
                    'w': This mode stands for "write mode" and allows you to write data to the file. If the file already exists, it will be truncated (emptied) before writing the new data. If the file doesn't exist, a new file will be created.

                    'b': This mode stands for "binary mode" and is used for working with binary files, such as image files. When working with binary data, it's important to open the file in binary mode to ensure that the data is read or written correctly without any unexpected conversions or modifications.
                    """
                    image_file.write(response.content)

                # Add success message to log file
                log_file.write(f'Success: {link}\n')
            else:
                # Add error message to log file if the download was unsuccessful
                log_file.write(f'Error: {link} - Failed to download\n')

        except Exception as e:
            # Add error message to log file if an exception occurred during download
            log_file.write(f'Error: {link} - {str(e)}\n')


#### Mini Project:
Step 1: Import the necessary modules
- Start by importing the required modules: random, time, and matplotlib.pyplot.

Step 2: Define the sorting algorithms
- Implement the bubble_sort() and insertion_sort() functions to perform bubble sort and insertion sort, respectively.
    - [here](https://codepumpkin.com/wp-content/uploads/2017/10/BubbleSort_Avg_case.gif) is a visualization of bubble sort
    
    ![bubble sort](https://codepumpkin.com/wp-content/uploads/2017/10/BubbleSort_Avg_case.gif)
    
    - here is a visualization of insertion sort
    
    ![insertion sort](https://i.pinimg.com/originals/92/b0/34/92b034385c440e08bc8551c97df0a2e3.gif)


Step 3: Initialize empty lists
- Create empty lists named input_sizes, bubble_sort_runtimes, and insertion_sort_runtimes to store the input sizes and runtimes for both algorithms.

Step 4: Set the maximum input size
- Set the value of max_input_size to specify the maximum input size for the sorting algorithms.

Step 5: Iterate over different input sizes
- Use a loop to iterate over a range of input sizes, starting from a minimum value (e.g., 100) and incrementing by a step size (e.g., 100) up to the maximum input size.

Step 6: Generate a random input dataset
- Inside the loop, generate a random list of numbers using random.sample() as the input dataset. The size of the list should correspond to the current input size.

Step 7: Measure the runtime of each sorting algorithm
- Measure the runtime of bubble sort and insertion sort for the current input dataset using time.time().
- Calculate the runtime by subtracting the start time from the end time.

Step 8: Store the input size and runtime
- Append the current input size to the input_sizes list.
- Append the runtime of bubble sort and insertion sort to their respective runtime lists.

Step 9: Plot the runtime data
- Use matplotlib.pyplot to plot the runtime data.
- Plot the runtime for bubble sort and insertion sort using the input_sizes list and the corresponding runtime lists.
- Add appropriate labels for the x-axis, y-axis, and the title of the plot.
- Include a legend to differentiate between the algorithms if necessary.

Step 10: Display the plot
- Call plt.show() to display the plot with the runtime data.


In [ ]:
import random
import time
import matplotlib.pyplot as plt
from tqdm import tqdm

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

# Initialize empty lists to store the input sizes and runtimes for each algorithm
input_sizes = []
bubble_sort_runtimes = []
insertion_sort_runtimes = []

# Set the maximum input size
max_input_size = 1000

# Iterate over different input sizes
for input_size in tqdm(range(100, max_input_size + 1, 100)):
    # Generate a random list of numbers as the input dataset
    data = list(range(input_size))
    random.shuffle(data)

    # Measure the runtime of bubble sort
    bubble_sort_start_time = time.time()
    bubble_sort(data.copy())
    bubble_sort_end_time = time.time()
    bubble_sort_runtime = bubble_sort_end_time - bubble_sort_start_time

    # Measure the runtime of insertion sort
    insertion_sort_start_time = time.time()
    insertion_sort(data.copy())
    insertion_sort_end_time = time.time()
    insertion_sort_runtime = insertion_sort_end_time - insertion_sort_start_time

    # Append the input size and runtimes to the lists
    input_sizes.append(input_size)
    bubble_sort_runtimes.append(bubble_sort_runtime)
    insertion_sort_runtimes.append(insertion_sort_runtime)

# Plot the runtime data for both algorithms
plt.plot(input_sizes, bubble_sort_runtimes, label='Bubble Sort')
plt.plot(input_sizes, insertion_sort_runtimes, label='Insertion Sort')
plt.xlabel('Input Size')
plt.ylabel('Runtime (seconds)')
plt.title('Runtime Analysis: Bubble Sort vs Insertion Sort')
plt.legend()
plt.show()


# Writing Markdown in Jupyter Notebook


## Introduction

Markdown is a lightweight and easy-to-use syntax for styling text on the web. It allows you to create formatted text using a plain text editor. Jupyter Notebooks have built-in support for displaying Markdown, which makes it a convenient platform for creating and sharing documents with formatted text, equations, images, and more.

## Step 1: Creating a Markdown Cell

To start writing Markdown in a Jupyter Notebook, you first need to create a Markdown cell.

1. Open your Jupyter notebook.
2. Click on the '+' button in the toolbar to create a new cell.
3. By default, the cell will be a code cell. To change it to a Markdown cell, you can click on the dropdown menu in the toolbar and select 'Markdown', or you can use a keyboard shortcut: press 'Esc' to enter command mode, then press 'M'.

## Step 2: Basic Formatting

Now that you've created a Markdown cell, you can start writing Markdown. Here are some basic formatting options:

- **Headers**: You can create headers using the '#' symbol. For example, '# Header 1' creates a level-1 header, '## Header 2' creates a level-2 header, and so on up to six levels.
- **Bold text**: You can make text bold by wrapping it with two asterisks or two underscores. For example, '**bold**' or '**bold**'.
- **Italic text**: You can make text italic by wrapping it with one asterisk or one underscore. For example, '*italic*' or '*italic*'.

## Step 3: Lists

Markdown supports both ordered and unordered lists.

- For ordered lists, you can simply number your items. For example:

1. Item 1
2. Item 2
3. Item 3

- For unordered lists, you can use the '-' or '*' symbol. For example:

- Item
- Item
- Item

## Step 4: Links and Images

You can also add links and images to your Markdown cells.

- To create a link, use the following syntax: `[Link Text](URL)`.
- To add an image, use the following syntax: `![Alt Text](URL or path to image)`. The alt text will be displayed if the image cannot be loaded.

## Step 5: Displaying Markdown

Once you've written your Markdown, you can display the formatted text by running the cell. You can do this by clicking the 'Run' button in the toolbar, or by using the keyboard shortcut 'Shift + Enter'.

## Step 6: Linking to Headers
Markdown allows you to create links to specific headers within your document. This can be useful for creating a table of contents or for making your document easier to navigate.

1. First, create a header. For example: `## My Header`.
2. Then, to create a link to that header elsewhere in your document, use the following syntax: `[Link Text](#my-header)`. Notice that the header text in the link spaces are replaced with hyphens.

[Here](#Writing-Markdown-in-Jupyter-Notebook) is an example.


## Step 7: Creating Tables
You can create tables in Markdown using a combination of pipes `|` and hyphens `-`. Here's an example:


| Header 1 | Header 2 | Header 3 |
| -------- | -------- | -------- |
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |


The first row defines the headers, the second row is a separator, and the remaining rows are the table's data.


## Step 8: Quoting Text
If you want to quote text, you can do so using the '>' symbol. For example:

> This is a quote.

## Step 9: Writing Mathematical Expressions
Markdown in Jupyter Notebooks also supports LaTeX for mathematical expressions. You can write inline expressions like this: `$e=mc^2$`, or display equations on their own line like this:
$$
f(x) = x^2
$$

## Step 10: Code Formatting
You can include formatted code within your Markdown text.

- For inline code, you can use single backticks: \`inline code\`.
- For blocks of code, you can use triple backticks and optionally specify the programming language:


```python
def hello_world():
    print("Hello, world!")
```

And there you go! With these tools, you should be able to create rich, well-formatted documents in Jupyter Notebook using Markdown. Happy writing!

## Numpy
- Python provides a vast ecosystem of packages and libraries that extend its capabilities and offer ready-to-use functionalities for various tasks.
- Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

### Installing NumPy
- NumPy can be installed using a package manager like pip. Open a terminal or command prompt and run the following command: `pip install numpy`
- Another way without using termial explicitly is to run this command in Jupyter `!pip install numpy`
- In Jupyter Notebook, the ! (exclamation mark) symbol is used to execute shell commands directly from a code cell. When you use ! followed by a command, Jupyter Notebook will treat it as a shell command and execute it in the underlying operating system.
- This will download and install the NumPy package on your system.

In [ ]:
# !pip install numpy

### Importing NumPy
- To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

- Once NumPy is installed, you can import it into your Python program using the import statement:
- By convention, np is used as an alias for NumPy to make it easier to reference its functions and objects.

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
c = np.array([[1,2,3],[4,5,6], [7]])   # Create a rank 2 array

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

### Array indexing

Numpy offers several ways to index into arrays.
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])
print('-----------')
# We can do all of the above in a single concise statement:
print(a[a > 2])

### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.


In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.